import { Hind_Siliguri } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import AuthProvider from "@providers/AuthProvider";
import MobileNav from "@components/MobileNav";
import Toploader from "@components/Toploader";

const Font_Hind_Siliguri = Hind_Siliguri({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "GariBd",
  description: "Generated by create next app",
};

export const revalidate = 0;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Font_Hind_Siliguri.className}>
        <Toploader />
        <Toaster />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
